/*Copyright (c) 2017-2018 vanenburgsoftware.com All Rights Reserved.
 This software is the confidential and proprietary information of vanenburgsoftware.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vanenburgsoftware.com*/
package com.testloginapp.hoursaccont1.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testloginapp.hoursaccont1.Department;
import com.testloginapp.hoursaccont1.Employee;
import com.testloginapp.hoursaccont1.HoursLogged;


/**
 * ServiceImpl object for domain model class Department.
 *
 * @see Department
 */
@Service("HoursAccOnt1.DepartmentService")
public class DepartmentServiceImpl implements DepartmentService {

    private static final Logger LOGGER = LoggerFactory.getLogger(DepartmentServiceImpl.class);

    @Autowired
	@Qualifier("HoursAccOnt1.HoursLoggedService")
	private HoursLoggedService hoursLoggedService;

    @Autowired
	@Qualifier("HoursAccOnt1.EmployeeService")
	private EmployeeService employeeService;

    @Autowired
    @Qualifier("HoursAccOnt1.DepartmentDao")
    private WMGenericDao<Department, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Department, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "HoursAccOnt1TransactionManager")
    @Override
	public Department create(Department department) {
        LOGGER.debug("Creating a new Department with information: {}", department);
        Department departmentCreated = this.wmGenericDao.create(department);
        if(departmentCreated.getEmployees() != null) {
            for(Employee employee : departmentCreated.getEmployees()) {
                employee.setDepartmentByDepartment(departmentCreated);
                LOGGER.debug("Creating a new child Employee with information: {}", employee);
                employeeService.create(employee);
            }
        }

        if(departmentCreated.getHoursLoggeds() != null) {
            for(HoursLogged hoursLogged : departmentCreated.getHoursLoggeds()) {
                hoursLogged.setDepartmentByDepartment(departmentCreated);
                LOGGER.debug("Creating a new child HoursLogged with information: {}", hoursLogged);
                hoursLoggedService.create(hoursLogged);
            }
        }
        return departmentCreated;
    }

	@Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
	@Override
	public Department getById(Integer departmentId) throws EntityNotFoundException {
        LOGGER.debug("Finding Department by id: {}", departmentId);
        Department department = this.wmGenericDao.findById(departmentId);
        if (department == null){
            LOGGER.debug("No Department found with id: {}", departmentId);
            throw new EntityNotFoundException(String.valueOf(departmentId));
        }
        return department;
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
	@Override
	public Department findById(Integer departmentId) {
        LOGGER.debug("Finding Department by id: {}", departmentId);
        return this.wmGenericDao.findById(departmentId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "HoursAccOnt1TransactionManager")
	@Override
	public Department update(Department department) throws EntityNotFoundException {
        LOGGER.debug("Updating Department with information: {}", department);
        this.wmGenericDao.update(department);

        Integer departmentId = department.getDeptId();

        return this.wmGenericDao.findById(departmentId);
    }

    @Transactional(value = "HoursAccOnt1TransactionManager")
	@Override
	public Department delete(Integer departmentId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Department with id: {}", departmentId);
        Department deleted = this.wmGenericDao.findById(departmentId);
        if (deleted == null) {
            LOGGER.debug("No Department found with id: {}", departmentId);
            throw new EntityNotFoundException(String.valueOf(departmentId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
	@Override
	public Page<Department> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Departments");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
    @Override
    public Page<Department> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Departments");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service HoursAccOnt1 for table Department to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
    @Override
    public Page<Employee> findAssociatedEmployees(Integer deptId, Pageable pageable) {
        LOGGER.debug("Fetching all associated employees");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("departmentByDepartment.deptId = '" + deptId + "'");

        return employeeService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
    @Override
    public Page<HoursLogged> findAssociatedHoursLoggeds(Integer deptId, Pageable pageable) {
        LOGGER.debug("Fetching all associated hoursLoggeds");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("departmentByDepartment.deptId = '" + deptId + "'");

        return hoursLoggedService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service HoursLoggedService instance
	 */
	protected void setHoursLoggedService(HoursLoggedService service) {
        this.hoursLoggedService = service;
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service EmployeeService instance
	 */
	protected void setEmployeeService(EmployeeService service) {
        this.employeeService = service;
    }

}

