/*Copyright (c) 2017-2018 vanenburgsoftware.com All Rights Reserved.
 This software is the confidential and proprietary information of vanenburgsoftware.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vanenburgsoftware.com*/
package com.testloginapp.hoursaccont1.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testloginapp.hoursaccont1.Employee;
import com.testloginapp.hoursaccont1.HoursLogged;


/**
 * ServiceImpl object for domain model class Employee.
 *
 * @see Employee
 */
@Service("HoursAccOnt1.EmployeeService")
public class EmployeeServiceImpl implements EmployeeService {

    private static final Logger LOGGER = LoggerFactory.getLogger(EmployeeServiceImpl.class);

    @Autowired
	@Qualifier("HoursAccOnt1.HoursLoggedService")
	private HoursLoggedService hoursLoggedService;

    @Autowired
    @Qualifier("HoursAccOnt1.EmployeeDao")
    private WMGenericDao<Employee, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Employee, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "HoursAccOnt1TransactionManager")
    @Override
	public Employee create(Employee employee) {
        LOGGER.debug("Creating a new Employee with information: {}", employee);
        Employee employeeCreated = this.wmGenericDao.create(employee);
        if(employeeCreated.getHoursLoggedsForEmplId() != null) {
            for(HoursLogged hoursLoggedsForEmplId : employeeCreated.getHoursLoggedsForEmplId()) {
                hoursLoggedsForEmplId.setEmployeeByEmplId(employeeCreated);
                LOGGER.debug("Creating a new child HoursLogged with information: {}", hoursLoggedsForEmplId);
                hoursLoggedService.create(hoursLoggedsForEmplId);
            }
        }

        if(employeeCreated.getHoursLoggedsForManagerId() != null) {
            for(HoursLogged hoursLoggedsForManagerId : employeeCreated.getHoursLoggedsForManagerId()) {
                hoursLoggedsForManagerId.setEmployeeByManagerId(employeeCreated);
                LOGGER.debug("Creating a new child HoursLogged with information: {}", hoursLoggedsForManagerId);
                hoursLoggedService.create(hoursLoggedsForManagerId);
            }
        }
        return employeeCreated;
    }

	@Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
	@Override
	public Employee getById(Integer employeeId) throws EntityNotFoundException {
        LOGGER.debug("Finding Employee by id: {}", employeeId);
        Employee employee = this.wmGenericDao.findById(employeeId);
        if (employee == null){
            LOGGER.debug("No Employee found with id: {}", employeeId);
            throw new EntityNotFoundException(String.valueOf(employeeId));
        }
        return employee;
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
	@Override
	public Employee findById(Integer employeeId) {
        LOGGER.debug("Finding Employee by id: {}", employeeId);
        return this.wmGenericDao.findById(employeeId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "HoursAccOnt1TransactionManager")
	@Override
	public Employee update(Employee employee) throws EntityNotFoundException {
        LOGGER.debug("Updating Employee with information: {}", employee);
        this.wmGenericDao.update(employee);

        Integer employeeId = employee.getEmplId();

        return this.wmGenericDao.findById(employeeId);
    }

    @Transactional(value = "HoursAccOnt1TransactionManager")
	@Override
	public Employee delete(Integer employeeId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Employee with id: {}", employeeId);
        Employee deleted = this.wmGenericDao.findById(employeeId);
        if (deleted == null) {
            LOGGER.debug("No Employee found with id: {}", employeeId);
            throw new EntityNotFoundException(String.valueOf(employeeId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
	@Override
	public Page<Employee> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Employees");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
    @Override
    public Page<Employee> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Employees");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service HoursAccOnt1 for table Employee to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
    @Override
    public Page<HoursLogged> findAssociatedHoursLoggedsForEmplId(Integer emplId, Pageable pageable) {
        LOGGER.debug("Fetching all associated hoursLoggedsForEmplId");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("employeeByEmplId.emplId = '" + emplId + "'");

        return hoursLoggedService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "HoursAccOnt1TransactionManager")
    @Override
    public Page<HoursLogged> findAssociatedHoursLoggedsForManagerId(Integer emplId, Pageable pageable) {
        LOGGER.debug("Fetching all associated hoursLoggedsForManagerId");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("employeeByManagerId.emplId = '" + emplId + "'");

        return hoursLoggedService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service HoursLoggedService instance
	 */
	protected void setHoursLoggedService(HoursLoggedService service) {
        this.hoursLoggedService = service;
    }

}

