/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.testloginapp.generatereports.controller;

import com.testloginapp.generatereports.GenerateReports;
import java.lang.String;
import javax.servlet.http.HttpServletResponse;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/generateReports")
public class GenerateReportsController {

    @Autowired
    private GenerateReports generateReports;

    @RequestMapping(value = "/generatePdfReport", method = RequestMethod.GET)
    public void generatePdfReport(@RequestParam(value = "jrxml", required = false) String jrxml, @RequestParam(value = "database", required = false) String database, HttpServletResponse response) {
        generateReports.generatePdfReport(jrxml, database, response);
    }
}
